eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8070/eureka/
spring:
  cloud:
    config:
      server:
        git:
          uri: file:///C:/propfiles
          clone-on-start: true
          default-label: master
  application:
    name: configserver
server:
  port: 8888
