server:
  port: 8083

spring:
  kafka:
    bootstrap-servers: localhost:9092
    streams:
      application-id: shipment-service
      default-key-serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      default-value-serde: org.springframework.kafka.support.serializer.JsonSerde
      auto-startup: true
      reset-offsets: true
